# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORrhuGr9Wv-cDsT5LIHxF9wuFAHAmue3
"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten , Dense
import matplotlib.pyplot as plt
import numpy as np

(x_train,y_train),(x_test,y_test)=mnist.load_data()

print(x_train.shape)
print(x_test.shape)

plt.imshow(x_train[0],cmap="gray")
plt.show()

print(y_train[0])

x_train=x_train/255.0
x_test=x_test/255.0

model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history=model.fit(x_train,y_train,epochs=10,validation_split=0.2)

test_loss,test_accuracy=model.evaluate(
    x_test,y_test)

print(test_accuracy)

prediction=model.predict(x_test)
np.argmax(prediction[1])

plt.imshow(x_test[1], cmap='gray')
plt.title(
    f"Predicted: {np.argmax(prediction[1])}"
)
plt.show()

model.save("digit_recognition_model.keras")

from tensorflow.keras.models import load_model

model = load_model(
    "digit_recognition_model.keras"
)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title("Model Accuracy")
plt.ylabel("Accuracy")
plt.xlabel("Epoch")

plt.legend(
    ['Train','Validation']
)

plt.show()